apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "9"
      kubernetes.io/change-cause: kubectl set image deployment hello-world-rest-api
        hello-world-rest-api=bproenca/hello-world-rest-api:0.0.5-SNAPSHOT --record=true
    creationTimestamp: "2020-04-09T23:04:31Z"
    generation: 24
    labels:
      app: hello-world-rest-api
    name: hello-world-rest-api
    namespace: default
    resourceVersion: "216653"
    selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/hello-world-rest-api
    uid: 78ac514f-7ab6-11ea-82e3-42010a8001a9
  spec:
    progressDeadlineSeconds: 600
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: hello-world-rest-api
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: hello-world-rest-api
      spec:
        containers:
        - image: bproenca/hello-world-rest-api:0.0.5-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: hello-world-rest-api
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 4
    conditions:
    - lastTransitionTime: "2020-04-10T17:36:26Z"
      lastUpdateTime: "2020-04-10T17:36:26Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2020-04-09T23:04:31Z"
      lastUpdateTime: "2020-04-10T17:53:42Z"
      message: ReplicaSet "hello-world-rest-api-69bf4fbc48" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 24
    readyReplicas: 4
    replicas: 4
    updatedReplicas: 4
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
---
  apiVersion: v1
  items:
  - apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: "2020-04-09T23:05:09Z"
      labels:
        app: hello-world-rest-api
      name: hello-world-rest-api
      namespace: default
      resourceVersion: "1828"
      selfLink: /api/v1/namespaces/default/services/hello-world-rest-api
      uid: 8f3ca959-7ab6-11ea-82e3-42010a8001a9
    spec:
      clusterIP: 10.103.13.103
      externalTrafficPolicy: Cluster
      ports:
      - nodePort: 32530
        port: 8080
        protocol: TCP
        targetPort: 8080
      selector:
        app: hello-world-rest-api
      sessionAffinity: None
      type: LoadBalancer
    status:
      loadBalancer:
        ingress:
        - ip: 35.193.33.62
  - apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: "2020-04-09T23:00:18Z"
      labels:
        component: apiserver
        provider: kubernetes
      name: kubernetes
      namespace: default
      resourceVersion: "150"
      selfLink: /api/v1/namespaces/default/services/kubernetes
      uid: e1d326a9-7ab5-11ea-82e3-42010a8001a9
    spec:
      clusterIP: 10.103.0.1
      ports:
      - name: https
        port: 443
        protocol: TCP
        targetPort: 443
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
  kind: List
  metadata:
    resourceVersion: ""
    selfLink: ""
  